<?php

namespace App\Console\Commands;

use App\Admin;
use App\CoreProtectBlock;
use App\Role;
use App\TokenUser;
use App\VoteUser;
use App\VoteUserEco;
use Carbon\Carbon;
use Illuminate\Console\Command;

class TransferVotes extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'czs:transfer-votes';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $a = [
            '_1ck0_',
            'lukaliso',
            'on_fire_craft',
            'fazer',
            'kubaendysvk',
            'petula69',
            'kojta645',
            'krystofmaster',
            'apu',
            'firey_',
            'alfneis ',
            'healy ',
            '_petko11_ ',
            'erika ',
            'denis22 ',
            'spetovka1 ',
            'fifa11 ',
            'mada204 ',
            'varmer127 ',
            'drz_sk ',
            'thehawk1998 ',
            'filipalfa ',
            'crazymalecz ',
            'matnew ',
            'bluehaxer ',
            'clarkins ',
            'mrkva_24 ',
            'piskejkonec ',
            'hanz ',
            'mleh ',
            'ercek_ ',
            'fabi_1 ',
            'dvojkaa ',
            'martin63 ',
            'psychykingpvp ',
            'shoqri ',
            'davidzadrazil ',
            'panhoumles ',
            'jonas_98_cze ',
            'kavy ',
            '__bigsmoke__ ',
            'meli27 ',
            'sh3rman ',
            'toxiczek ',
            'kocikcz ',
            'baarbuchaa ',
            'tedias ',
            'pandulak ',
            'tomeccko ',
            'athentios ',
            'lukaso123 ',
            'k_a_s_p_i ',
            'flatron_cz ',
            'yeti107owo ',
            'timko1458 ',
            'metalgameryt ',
            'mrfoxes ',
            'johnysakind ',
            'deathead ',
            '15majda08 ',
            'jejda ',
            'matejko ',
            'kjdonald ',
            'miskogayj ',
            'radekgamersk ',
            'indis ',
            'policajtka001 ',
            'elitekaja ',
            'divix1231 ',
            'nandejtyboty ',
            'zakar_12888 ',
            'matorexcz28 ',
            'noneskill ',
            'phsyrue ',
            'babyhippo1020 ',
            'zuzu ',
            'promasterelite ',
            'haqo33 ',
            'lukasyn ',
            'tatyrek ',
            'tomaskana07 ',
            'jindrisak ',
            'ewaya ',
            'scaryasek ',
            'mishanetty ',
            'popocek1234 ',
            'katerinaeff ',
            'myrofight ',
            '8lank ',
            'flexa21 ',
            'momo356 ',
            'anycoleste ',
            'volekbolek ',
            'epxol ',
            'kubis ',
            'atlantis_samo_ ',
            'wqrthy ',
            'lolikbitch ',
            'castorisdebaas ',
            'antizaneta ',
            'justfazer ',
            'zidan9 ',
            '_n_f_e_d_ ',
            'asairskill ',
            '69carloxss_ ',
            '_yakkub_ ',
            'fabiaum ',
            'risozabijak ',
            'gauel ',
            '_bad_gui_ ',
            'cernemore ',
            'antref ',
            'kasperus ',
            'martwin31 ',
            'tycycz ',
            'hugisjepan ',
            'g_e_r_1_s ',
            'herbylp ',
            'brelum ',
            'sickmad ',
            'ivarrsier ',
            'bujon ',
            'power_hd ',
            'fuuny ',
            'radyskri ',
            'sabousek ',
            'fakued_guela ',
            'barackobama2020 ',
            'terrka15 ',
            'dodo0603 ',
            'ev3rnis0 ',
            'raarka ',
            'kebabnik337 ',
            'irxxdy ',
            'itzdufikcze ',
            'mata9652 ',
            'ffraxic ',
            'tonda_wole ',
            'george_dk ',
            'werd ',
            'uzicectv ',
            'ondrejjr123 ',
            'redwinee ',
            'virkie ',
            'nopo ',
            'pidimidii ',
            'maxi_cek ',
            'daniel10kd ',
            'annaphantomhive_ ',
            'smekca ',
            'trpajzlik ',
            'cysgodol ',
            'agrael ',
            '_piticko ',
            'hantuari_cz ',
            'nir4rer ',
            'bakuba134 ',
            'maner ',
            'tommccz ',
            'vaxx99 ',
            'luckyjohny ',
            'i_c_e ',
            '966dominik ',
            '_tomasss_ ',
            'unknown_gamer600 ',
            'patricius1000 ',
            'wiseon3 ',
            'kiwyi_cz ',
            'koudelaaa ',
            'mrlimers ',
            'n_a_t_y_ ',
            'stealthninja55 ',
            'lopatik658947 ',
            '_ivi_ ',
            'postradatel ',
            'hanoslav ',
            'matthewvbos ',
            'etela ',
            'verstergaard ',
            'honza006 ',
            'bobek123 ',
            'k1b0rk ',
            'steewe ',
            'krallangusta ',
            'ondraskogames ',
            '_atikin_ ',
            'fukume ',
            'hrdlik98 ',
            'youtubexxxxx ',
            'panlanc ',
            'strom ',
            'theflamebower ',
            'k0udelka15 ',
            'creer09 ',
            'feldauwu ',
            'padavan ',
            'kavaler152 ',
            'c3te_ ',
            'elka_michal ',
            '_kmg ',
            'angevina ',
            'kolikoliko ',
            'petromil ',
            'javicek ',
            'enzovar ',
            'gamex_cz_yt ',
            'maikator_cz ',
            'zdendapoloreich_ ',
            'matmig123 ',
            'micky ',
            'mesiccz ',
            'sypendy ',
            'ruth_21 ',
            'ledvax ',
            'xtobin_ ',
            'mickfearson ',
            'ragnarlodbrok_v ',
            'chutnej ',
            'xsattan ',
            'rookmantv ',
            '__mask ',
            'vrbi_ ',
            'zfiky ',
            'mildchildmines ',
            'm1chal184 ',
            'lyxancz ',
            'robik120 ',
            'dragon570 ',
            'sexyk ',
            '_tracker__ ',
            'animegurl1 ',
            'koalagurl ',
            'gamerskcz ',
            'adolfgottem ',
            'jendajede ',
            'saijmon ',
            'szuuuli ',
            'dollarprince ',
            'houbacek_ratata ',
            'elnum_dodo ',
            'brankojjjj ',
            'mrvojteewcze ',
            'islington ',
            'marospk347 ',
            'dzeeralt ',
            'weenxiz_ ',
            'invader88 ',
            'merciee_ ',
            'surfmansgo ',
            'p0lix77 ',
            'lovewillkillu ',
            'lostbaufax ',
            'lokomotivafbi ',
            'miki2506 ',
            'supafit ',
            'm4tej_09 ',
            'dr3_4m ',
            'fifahoko156 ',
            'jckpt ',
            'quino ',
            'lariel528 ',
            'arch00 ',
            'dustertv ',
            'moonosak ',
            'tomasion ',
            '_justapexx_ ',
            'pandrmiacz ',
            'elika_flores ',
            'bacazrout ',
            'azurit ',
            'frosty070 ',
            'tanoshimeyocz ',
            'cutekate808cz ',
            'djvister ',
            'fillacz ',
            'punko69 ',
            'adkos ',
            'ximoogg ',
            'nelinka_25 ',
            'ajemgroot ',
            '_auxi_ ',
            'douchax ',
            'bartyys ',
            't3exiss ',
            'slehy ',
            'lacta ',
            'benjados ',
            'hanzzz ',
            'luckyj0hny',
            'xxzrsk4xx',
            'zmetekk',
            'jandlys',
            'eddiebylike',
            'in3edyourskill',
            'romo2003',
            'pop558',
            'danca_7',
            'raidenncz',
            'vidra556kik',
            'bluestyle',
            'maxtad',
            'terezos',
            'lulo1001',
            'zirous123',
            'terezka',
            'iiduxsstar',
            'doctordiscocz',
            'dogshoker',
            'beaboy',
            'kubicek3271',
            'pelkodohuby',
            'the_only_dodo',
            'siemson',
            'danielyk',
            'maxipesfik1',
            'synnxi',
            'redangelxxx',
            'karlik900',
            'loraxsis',
            'xxmiwumitaruxx',
            'artesis',
            'lindorai',
            'xkrasax',
            'dogzewy',
            'lolitka666',
            'vaseek',
            'dieselthelad',
            'knightetiam',
            'pabbl0',
            'lordmk',
            'itzjeffciv',
            'plot2',
            'schlehofer',
            'duffa',
            'onunany_syr',
            '_m_e_s_k_',
        ];
        foreach ($a as $name) {
            shell_exec('sudo screen -S Survival -p 0 -X stuff " lp user ' . $name . ' clear' . '\n";');
        }

    }
}
